<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }

            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"表彰荣誉档案管理",
                        "menuJump":"列表",
                        "tableName":"biaozhangrongyu"
                    }
                ],
                "menu":"表彰荣誉档案管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"学历管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXueli"
                    }

                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"工资晋级档案管理",
                        "menuJump":"列表",
                        "tableName":"gongzijishengjinsheng"
                    }
                ],
                "menu":"工资晋级档案管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"工作经历档案管理",
                        "menuJump":"列表",
                        "tableName":"gongzjinbgyan"
                    }
                ],
                "menu":"工作经历档案管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"年度考核档案管理",
                        "menuJump":"列表",
                        "tableName":"niandukaohe"
                    }
                ],
                "menu":"年度考核档案管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"社会保险档案管理",
                        "menuJump":"列表",
                        "tableName":"shehuibaoxian"
                    }
                ],
                "menu":"社会保险档案管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学历档案管理",
                        "menuJump":"列表",
                        "tableName":"xueli"
                    }
                ],
                "menu":"学历档案管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"职工管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"职工管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"政审档案管理",
                        "menuJump":"列表",
                        "tableName":"zhengshen"
                    }
                ],
                "menu":"政审档案管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"职称档案管理",
                        "menuJump":"列表",
                        "tableName":"zhicheng"
                    }
                ],
                "menu":"职称档案管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"职务档案管理",
                        "menuJump":"列表",
                        "tableName":"zhiwu"
                    }
                ],
                "menu":"职务档案管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"表彰荣誉档案管理",
	                    "menuJump":"列表",
	                    "tableName":"biaozhangrongyu"
	                }
	            ],
	            "menu":"表彰荣誉档案管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"工资晋级档案管理",
	                    "menuJump":"列表",
	                    "tableName":"gongzijishengjinsheng"
	                }
	            ],
	            "menu":"工资晋级档案管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"工作经历档案管理",
	                    "menuJump":"列表",
	                    "tableName":"gongzjinbgyan"
	                }
	            ],
	            "menu":"工作经历档案管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"年度考核档案管理",
	                    "menuJump":"列表",
	                    "tableName":"niandukaohe"
	                }
	            ],
	            "menu":"年度考核档案管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"社会保险档案管理",
	                    "menuJump":"列表",
	                    "tableName":"shehuibaoxian"
	                }
	            ],
	            "menu":"社会保险档案管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"学历档案管理",
	                    "menuJump":"列表",
	                    "tableName":"xueli"
	                }
	            ],
	            "menu":"学历档案管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"政审档案管理",
	                    "menuJump":"列表",
	                    "tableName":"zhengshen"
	                }
	            ],
	            "menu":"政审档案管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"职称档案管理",
	                    "menuJump":"列表",
	                    "tableName":"zhicheng"
	                }
	            ],
	            "menu":"职称档案管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"职务档案管理",
	                    "menuJump":"列表",
	                    "tableName":"zhiwu"
	                }
	            ],
	            "menu":"职务档案管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"职工",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
